from pathlib import Path
p=Path('workflow.py');s=p.read_text(encoding='utf-8')
s=s.replace('scene_snapshot, plan_source\n', 'scene_snapshot, plan_source, validate_project\n')
s=s.replace("        from professional import parse_fdx\n        try:", "        from professional import parse_fdx\n        previous_data, previous_path, previous_saved = self.project_data(), self.path, self._last_saved\n        try:")
s=s.replace("            self.clear_session_recovery()\n            self.load_project(data, path if suffix == '.eguion' else None)", "            validate_project(data)\n            self.load_project(data, path if suffix == '.eguion' else None)\n            self.clear_session_recovery()")
s=s.replace("            QMessageBox.critical(self, 'No se pudo abrir', str(error)); return False", "            self.load_project(previous_data, previous_path); self._last_saved = previous_saved; self.check_workflow()\n            QMessageBox.critical(self, 'No se pudo abrir', str(error)); return False")
s=s.replace('    def load_project(self, data, path=None):\n        self._loading', '    def load_project(self, data, path=None):\n        validate_project(data)\n        self._loading')
s=s.replace("            self.load_project(data, None); self._last_saved = ''; self.dirty = True; dialog.accept()", "            validate_project(data)\n            self.load_project(data, None); self._last_saved = ''; self.dirty = True; dialog.accept()")
s=s.replace("            metadata = {**self.project_info, 'titulo':", "            aliases = {'productora': 'company', 'director': 'director', 'productor': 'producer', 'guionista': 'writer', 'version_guion': 'script_version'}\n            metadata = {**{key: self.project_info.get(value, '') for key, value in aliases.items()}, **self.project_info, 'titulo':")
p.write_text(s,encoding='utf-8')
p=Path('verify.py');s=p.read_text(encoding='utf-8').replace("assert data['blocks'] == blocks", "assert [{k: b[k] for k in ('type', 'text')} for b in data['blocks']] == blocks\n    assert data['blocks'] == window.editor.blocks()")
p.write_text(s,encoding='utf-8')
p=Path('workflow_ui.py');s=p.read_text(encoding='utf-8')
s=s.replace("La moneda y los cambios se administran en Proyecto.'", "La moneda y los cambios se administran en Proyecto. En una plantilla, usa {{TITULO}} y {{MONEDA}} para el encabezado; en una fila de detalle: {{CONCEPTO}}, {{CATEGORIA}}, {{CANTIDAD}}, {{JORNADAS}}, {{PRECIO}}, {{TOTAL_LINEA}} y {{NOTAS}}.'")
p.write_text(s,encoding='utf-8')
